package constants;

public enum Commands {
    SIGNUP,
    LOGIN,
    LOGOUT,
    ADD_FLIGHT,
    DISPLAY_MY_FLIGHTS,
    ADD_FLIGHT_DETAILS,
    DELETE_FLIGHTS,
    CANCEL_FLIGHT,
    PERSIST_FLIGHTS,
    PERSIST_USERS,
    DEFAULT_COMMAND
}
